language: java
jdk: oraclejdk8
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: qIG7zpjubVJFKMSxq+Pl3MWQbC/Mk4k86iN7An4Zz8Yci0yntjcWNsY6gz9078sT1yqFS03dTzPnTSrMkYwSEZzXHZ5NDJ8/gy2q44BMsMLUChjIGAAnozrZhM0BqNN3uPHdAl+DgE+BTMvEKCh/8qWs7MC9AvP2Hk6PbCkD9JtXpoDioMhvDDuoIYk5zj2yAsNnSAdsNy8pCrzVdf7FwXiojnXWJFO60oQF+TyZ8gfOq/BjbCtJ7KV+3EYWCzoPKE/0G19/Dhrqk8jWl53+uwLBJDJ6EcqLhbRVuhMRAiDZ90BcpCGxRMNA5dTOezFBycLFHRnryWEcZnnIC3U8wAf5sS95UVaeToYaFm9IWA0WmGeLqBZ1rVNhd/PZS6poUqPZb7K3MNuK+WnZYsaU85Hc75Tj57zF6M4Un9LDUjnas4Vt8GMfKkSwdM77k1WKt5YreGK8QOu7mBOtNzuOdWwCFkW1aYpeu90bLpWVOrS+nPni8ReW7/m6cSr11wlfEKJUn3Lmjfk1ZcqjyOVbmHoxBoDr9n27ot57duGmc8YmYu6ec9Jq3kSvFv7vU0RZYmzIt16yRMyo11MrzJVNbb7ZnQwbUtAryvwgfkqU5VQz4EykLbfxgLHXBRj2LfAxa8+sRqQhhP6m2M17F7mKwoR7TmrkDsZLzxA3RpKGaqw=
